-- "distance" = {"Title", "Subtext", "file_name.png"}
achievementTable = {
	{60, "Average Oak Tree", "An admirable start for a squirrel", "achievement_oak_tree.png"},
	{100, "Rockefeller Xmas Tree", "Rockin' Around the Christmas Tree", "achievement_xmas_tree.png"},
	{176, "Pine Tree", "Pine cones aren't enough", "achievement_pine_tree.png"},
	{286, "Giant Sequoia Tree", "An up-and-coming neighborhood", "achievement_sequoia.png"},
	{379, "Record Breaking Redwood", "Big Red", "achievement_redwood.png"},
	{455, "Great Pyramid of Giza", "On the way to Ra", "achievement_pyramid_giza.png"},
	{555, "Washington Monument", "Washingsquirrel, the first squirrel president", "achievement_washington_monument.png"},
	{841, "U.S. Steel Tower", "Developers! Developers!", "achievement_steel_tower.png"},
	{986, "Eiffel Tower", "Do squirrels like cheese?", "achievement_eiffel_tower.png"},
	{1250, "Empire State Building", "More like Empire Squirrel Building", "achievement_empire_state_building.png"},
	{1451, "Sears Tower", "Wish I had brought my windbreaker", "achievement_sears_tower.png"},
	{2717, "Burj Khalifa", "Are there even squirrels in Dubai?", "achievement_burj_khalifa.png"},
	{3000, "Cumulus Clouds", "Into the clouds", "achievement_clouds.png"},
	{5280, "1 Mile Up", "Mile high club", "achievement_one_mile.png"},
	{9001, "Power Level", "What does the scouter say?", "achievement_power_level.png"},
	{10663, "Mt. Botzer", "Developers!", "achievement_mt_botzer.png"},
	{28000, "Lost Balloon", "This is pretty high \"Up\" here isn't it?", "achievement_balloon.png"},
	{29029, "Mt. Everest", "I should be hibernating right now", "achievement_mt_everest.png"},
	{35000, "Boeing 757", "Now seating squirrels", "achievement_boeing.png"},
	{327000, "Space", "Where no squirrel has gone before", "achievement_space.png"},
	{1360000, "ISS", "No raccoons allowed", "achievement_iss.png"},
	{5443680, "Sputnik 2", "Squilnit the Soviet Squirrel", "achievement_sputnik.png"},
	{1200000000, "The Moon", "One small step for man, one giant leap for a squirrel", "achievement_moon.png"},
	{9999999999, "Congratulations!", "You've won!!! Although this height seems a bit suspicious...", "achievement31.png"},
}